const TEAM_NAMES_ES: Record<string, string> = {
  algeria: "Argelia",
  argentina: "Argentina",
  australia: "Australia",
  austria: "Austria",
  belgium: "Bélgica",
  brazil: "Brasil",
  "bosnia and herzegovina": "Bosnia y Herzegovina",
  canada: "Canadá",
  chile: "Chile",
  china: "China",
  colombia: "Colombia",
  "costa rica": "Costa Rica",
  croatia: "Croacia",
  denmark: "Dinamarca",
  ecuador: "Ecuador",
  egypt: "Egipto",
  england: "Inglaterra",
  france: "Francia",
  germany: "Alemania",
  ghana: "Ghana",
  greece: "Grecia",
  honduras: "Honduras",
  iran: "Irán",
  iraq: "Irak",
  italy: "Italia",
  japan: "Japón",
  mexico: "México",
  morocco: "Marruecos",
  netherlands: "Países Bajos",
  "new zealand": "Nueva Zelanda",
  nigeria: "Nigeria",
  norway: "Noruega",
  panama: "Panamá",
  paraguay: "Paraguay",
  peru: "Perú",
  poland: "Polonia",
  portugal: "Portugal",
  qatar: "Catar",
  romania: "Rumania",
  "saudi arabia": "Arabia Saudita",
  scotland: "Escocia",
  senegal: "Senegal",
  serbia: "Serbia",
  slovakia: "Eslovaquia",
  slovenia: "Eslovenia",
  "south africa": "Sudáfrica",
  "south korea": "Corea del Sur",
  sudafrica: "Sudáfrica",
  spain: "España",
  espana: "España",
  sweden: "Suecia",
  switzerland: "Suiza",
  tunisia: "Túnez",
  turkey: "Turquía",
  turquia: "Turquía",
  ukraine: "Ucrania",
  "united states": "Estados Unidos",
  uruguay: "Uruguay",
  wales: "Gales",
};

export function teamNameEs(name: string) {
  const normalized = name
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");

  return TEAM_NAMES_ES[normalized] ?? name;
}
